/**
 * Generate slimmed copies of the chords-db shape libraries.
 *
 * chords-db stores a `midi` array (and sometimes a `capo` flag) on every chord
 * position. Nothing in this package reads either — `dbPositionToChord` only
 * uses frets/fingers/baseFret/barres — but they are pure bundle weight for
 * every consumer, and the libraries are imported eagerly at module scope.
 *
 * Source data: @tombatossals/chords-db (MIT). This writes a field-subset copy;
 * the shapes themselves are unmodified.
 *
 * Output is gitignored and regenerated by the build/test/lint scripts, so the
 * generated files always match the installed chords-db version.
 */
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "src", "generated");

const LIBRARIES = ["guitar", "ukulele"];
/** Position fields this package actually reads. */
const KEEP = ["frets", "fingers", "baseFret", "barres"];

mkdirSync(outDir, { recursive: true });

const pkg = JSON.parse(
  readFileSync(require.resolve("@tombatossals/chords-db/package.json"), "utf8"),
);

for (const name of LIBRARIES) {
  const srcPath = require.resolve(`@tombatossals/chords-db/lib/${name}.json`);
  const db = JSON.parse(readFileSync(srcPath, "utf8"));

  for (const entries of Object.values(db.chords)) {
    for (const entry of entries) {
      entry.positions = entry.positions.map((pos) =>
        Object.fromEntries(KEEP.filter((k) => k in pos).map((k) => [k, pos[k]])),
      );
    }
  }
  db._source = `@tombatossals/chords-db@${pkg.version} (MIT) — positions reduced to ${KEEP.join("/")}`;

  const outPath = join(outDir, `${name}.slim.json`);
  writeFileSync(outPath, JSON.stringify(db));

  const before = readFileSync(srcPath).byteLength;
  const after = readFileSync(outPath).byteLength;
  const pct = Math.round((1 - after / before) * 100);
  console.log(
    `chords-db ${name}: ${before.toLocaleString()} → ${after.toLocaleString()} bytes (-${pct}%)`,
  );
}
